---
- name: installing Metricbest
  hosts: webservers
  become: yes
  tasks:

  - name: Download Metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Instal Metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Copy config
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable the Metricbeat docker
    command: metricbeat modules enable docker

  - name: Setup Metricbeat
    command: metricbeat setup

  - name: Start metric beat service
    command: service metricbeat start

  - name: Metricbeat -e command
    command: metricbeat setup -e

  - name: Enable Metricbeat service on boot
    systemd:
      name: metricbeat
      enabled: yes
